services:
  - type: web
    name: blood-cancer-app
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    pythonVersion: 3.10.13